package main

import (
	"bufio"
	"database/sql"
	_ "github.com/lib/pq"
	"log"
	"os"
	"strings"
)

func createTable(db *sql.DB) {
	_, err := db.Exec(`CREATE TABLE IF NOT EXISTS places (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		name varchar(255) NOT NULL,
		address varchar(255) NOT NULL,
   	 	phone varchar(255) NOT NULL,
		longitude real NOT NULL,
		latitude real NOT NULL
		)`)
	if err != nil {
		log.Fatal(err)
	}
}

func csvToDB(db *sql.DB, filePath string) {
	f, err := os.Open(filePath)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	scanner.Split(bufio.ScanLines)
	scanner.Scan()
	pIdx := 0
	for scanner.Scan() {
		rec := strings.Split(scanner.Text(), "\t")
		sqlStatement := `INSERT INTO places (id, name, address, phone, longitude, latitude) values ($1, $2, $3, $4, $5, $6)`
		_, err = db.Exec(sqlStatement, rec[0], rec[1], rec[2], rec[3], rec[4], rec[5])
		if err != nil {
			log.Fatal(err)
		}
		pIdx++
	}
}

func main() {
	conninfo := "dbname=Day03 user=ougirez password=12345 host=localhost sslmode=disable"
	db, err := sql.Open("postgres", conninfo)
	defer db.Close()
	if err != nil {
		log.Fatal(err)
	}
	createTable(db)
	csvToDB(db, "./data.csv")
}
